[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/"
]

# Solidity compiler version
solc_version = "0.8.24"
evm_version = "cancun"

# Optimization
optimizer = true
optimizer_runs = 200
